# Generated by Django 4.2.7 on 2023-12-02 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_device_device_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numericallog",
            name="date_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Date and time",
            ),
        ),
    ]
