# Generated by Django 4.2.7 on 2023-12-02 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_numericallog_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="expiry",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Expiry Date"
            ),
        ),
    ]
