# Generated by Django 4.2.7 on 2023-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_device_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="numericallog",
            name="data_label",
            field=models.CharField(default="x", max_length=50, verbose_name="Lable"),
        ),
    ]
