# Generated by Django 4.2.7 on 2023-12-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_numericallog_data_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPIOPin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Pin Name")),
                ("pin", models.SmallIntegerField(verbose_name="GPIO pin")),
            ],
            options={
                "verbose_name": "GPIOPin",
                "verbose_name_plural": "GPIOPins",
            },
        ),
    ]
