# Generated by Django 4.2.7 on 2023-12-20 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_gpiopin"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpiopin",
            name="device",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.device",
                verbose_name="Device",
            ),
        ),
    ]
