# Generated by Django 4.2.7 on 2023-12-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_apikey_options_alter_gpiooutputpin_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpiooutputpin",
            name="affects_variable",
            field=models.BooleanField(default=False),
        ),
    ]
