# Generated by Django 4.2.7 on 2023-12-24 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_gpiooutputpin_affects_variable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gpiooutputpin",
            name="affects_variable",
        ),
    ]
