# Generated by Django 5.0.6 on 2024-05-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_gpiooutputpin_affects_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0, verbose_name='Latitude')),
                ('lng', models.FloatField(default=0, verbose_name='Longtitude')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device', verbose_name='Device')),
            ],
        ),
    ]
