# Generated by Django 5.0.6 on 2024-05-14 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_locationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Date and time'),
        ),
    ]
