# Generated by Django 5.0.6 on 2024-06-21 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_expirabletoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttBrokerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=1883)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(max_length=255)),
                ('profile_settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profilesettings', verbose_name='Profile')),
            ],
        ),
    ]
