# Generated by Django 5.0.6 on 2024-06-21 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_host_mqttbrokersettings_broker_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='mqtt_broker',
        ),
        migrations.AddField(
            model_name='mqttbrokersettings',
            name='profile_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profilesettings', verbose_name='profile_settings'),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profile'),
        ),
    ]
