# Generated by Django 5.0.6 on 2024-10-06 08:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_profilesettings_mqtt_broker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(default='name', max_length=64, verbose_name='Name')),
                ('entry_id', models.TextField(unique=True, verbose_name='Identifier')),
            ],
            options={
                'verbose_name': 'Inventory Entries',
            },
        ),
        migrations.CreateModel(
            name='InventoryEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=3, verbose_name='Log Type')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Timestamp')),
                ('parent_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventoryentry')),
            ],
        ),
    ]
