# Generated by Django 5.0.6 on 2024-10-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_inventoryentry_inventoryentrylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.device', verbose_name='Device'),
        ),
    ]
