# Generated by Django 5.0.6 on 2025-04-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_device_is_active_device_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="never_expires",
            field=models.BooleanField(default=False, verbose_name="Never Expires"),
        ),
    ]
