# Generated by Django 5.0.6 on 2024-10-09 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_inventoryentry_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryentry',
            name='entry_type',
            field=models.CharField(choices=[('Inventory', 'Inventory'), ('Attendance', 'Attendance')], default='Inventory', max_length=16),
        ),
        migrations.AlterField(
            model_name='inventoryentry',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device', verbose_name='Device'),
        ),
    ]
