# Generated by Django 5.0.6 on 2025-10-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_apikey_never_expires"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Data")),
                (
                    "date_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date and time"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.device",
                        verbose_name="Device",
                    ),
                ),
            ],
            options={
                "verbose_name": "Generic Log",
                "verbose_name_plural": "Generic Logs",
                "ordering": ["-date_time"],
            },
        ),
    ]
